#!/bin/bash

echo "Compiling the overlay from .dts to .dtbo"
filename=$(basename "$1")
extension="${filename##*.}"
filename="${filename%.*}"

outfile="${filename}-00A0.dtbo"

dtc -O dtb -o ${outfile} -b 0 -@ $1

cp $outfile /lib/firmware/
