#########
#
# Build the various demos
#
#
BIN-y += fire
BIN-y += life
BIN-y += cube-life
BIN-y += matrix-test
BIN-y += identify
BIN-y += spi

fire.srcs += fire.c
life.srcs += life.c
identify.srcs += identify.c
cube-life.srcs += cube-life.c
matrix-test.srcs += matrix-test.c
spi.srcs += spi.c

include ../../Makefile.common

